### ISSUE TITLE
Internalization of the website

### ISSUE THREAD

**Issue by CarlSchwan** [popey/makealinux.app#15]
Hi, I think it would be a great idea to make the website translatable. We have a tool in KDE that helps with extracting po files from Hugo projects: https://invent.kde.org/websites/hugo-i18n but it probably still needs a place for translators to translate them (e.g weblate) and the theme will probably need to get some changes.

Would you like me to give it a try and set everything up?

**Comment by popey** [comment]
Thanks for the issue. I'm actually planning to rebooting the site. As part of that re-write I will indeed make sure it's translatable. I'll leave this issue open to remind me :)

**Comment by CarlSchwan** [comment]
Nice, let me know if you need help :)

**Comment by roughpandaz** [comment]
@popey - just trying to see if there's been any progress on this :) 
P.S saw this on Hackernews!

**Comment by victorhck** [comment]
no news about this in 2 years?

**Comment by popey** [comment]
Thanks for the issue. Sorry, it's taken a while to get back to this. 
I've decided to reboot this initiative and move the repo to a new location while we work on it. 

I hope you'll join us there. I am building the new site with internationalization in mind. :) 

https://github.com/makealinuxapp/makealinuxapp
