### ISSUE TITLE
Add Tauri as Electron alternative

### ISSUE THREAD

**Issue by KaKi87** [popey/makealinux.app#18]
Hi,

Just like Electron, [Tauri](https://tauri.app/) allows web devs to make cross-platform desktop apps, but using system renderers (Webkit on Linux & Mac, Edge on Windows) instead of embedding Chrome, thus reducing package size and resources usage.

The JS API is still far from Electron's so it can't replace all use cases yet, but it's a work in progress.

Thanks

**Comment by popey** [comment]
Thanks for the issue. Sorry, it's taken a while to get back to this. 
I've decided to reboot this initiative and move the repo to a new location while we work on it. 

I hope you'll join us there. 

https://github.com/makealinuxapp/makealinuxapp
