### ISSUE TITLE
Add AppCenter to “Sharing Your Creation”

### ISSUE THREAD

**Issue by cassidyjames** [popey/makealinux.app#3]
elementary OS is a target distribution with a developer guide, but AppCenter is a build service and app store—especially with our work to move to be a Flatpak remote. It is also the only distribution method I know of with monetization built in.

**Comment by popey** [comment]
@cassidyjames Great idea. Where can I find an SVG of the AppCenter icon? I did have a rummage in the source and packaged versions but couldn't find it.

**Comment by cassidyjames** [comment]
PR incoming in a few mins 😉
