### ISSUE TITLE
Add Qt to "Where to start"

### ISSUE THREAD

**Issue by probonopd** [popey/makealinux.app#4]
One should probably emphasize that besides reaching most Linux distributions, applications written in Qt can also run natively on Windows, macOS, Android, and embedded systems without changes in the codebase.

> Qt is a free and open-source widget toolkit for creating graphical user interfaces as well as cross-platform applications that run on various software and hardware platforms such as Linux, Windows, macOS, Android or embedded systems with little or no change in the underlying codebase while still being a native application with native capabilities and speed.

https://en.wikipedia.org/wiki/Qt_(software)

**Comment by probonopd** [comment]
Wdyt?

**Comment by probonopd** [comment]
Ping.

**Comment by jtagcat** [comment]
(I'm not very involved with this repo, but I'd suggest you to make a MR.)

**Comment by popey** [comment]
Thanks for the issue. Sorry, it's taken a while to get back to this. 
I've decided to reboot this initiative and move the repo to a new location while we work on it. 

I hope you'll join us there. 

https://github.com/makealinuxapp/makealinuxapp
