### ISSUE TITLE
Add a source of "apps wish list".

### ISSUE THREAD

**Issue by gabofer82** [popey/makealinux.app#8]
I wonder why I can't find any wish list for Linux apps. It seems that the community does not recognize the lack of necessary applications for Linux.
I suppose it would be a great idea for the site to include a link to a site dedicated to publishing that is missing from the ecosystem of Linux applications.

Congratulations for this site!

**Comment by probonopd** [comment]
> site dedicated to publishing that is missing from the ecosystem of Linux applications

With "publishing", do you mean that publishing-related applications are missing on Linux? Maybe this can serve as a starter:

https://github.com/AppImage/AppImageKit/wiki/Libre-Graphics-Suite

**Comment by popey** [comment]
I know of plenty of places where people lament the fact that a specific proprietary (or indeed open source) application isn't available on Linux. That's more a porting effort, and business decisions by the app developer / publisher. 

I don't really know of any central wishlists though.

**Comment by jtagcat** [comment]
Here you go: https://github.com/jtagcat/linux-wishlist

**Comment by jtagcat** [comment]
Here you go: https://github.com/jtagcat/linux-wishlist

Now, start adding stuff.

e: remind me to make a pr (to close this issue) to link to it in the site with something like don't know what to make but want to make something (!! this could result in many people making a thing and abandoning them, tldr low quality-ish result)

**Comment by gabofer82** [comment]
> > site dedicated to publishing that is missing from the ecosystem of Linux applications
> 
> With "publishing", do you mean that publishing-related applications are missing on Linux? Maybe this can serve as a starter:
> 
> https://github.com/AppImage/AppImageKit/wiki/Libre-Graphics-Suite

Sorry, i meant "site with a public wish list".

**Comment by popey** [comment]
Thanks for the issue. Sorry, it's taken a while to get back to this. 
I've decided to reboot this initiative and move the repo to a new location while we work on it. 

I hope you'll join us there. 

https://github.com/makealinuxapp/makealinuxapp
